name: Lint

on:
  push:
    # On other branches the `pull_request` trigger will be used
    branches: [current, next]

  pull_request:
    types: [opened, edited, reopened, synchronize]

permissions:
  contents: read
  
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install pagefind
      uses: jaxxstorm/action-install-gh-release@v1.12.0
      with:
          repo: cloudcannon/pagefind
    - uses: actions/checkout@v4.1.6
    - name: Set up Python 3.8
      uses: actions/setup-python@v5
      with:
        python-version: 3.8
    - name: Install dependencies
      run: pip install -r requirements.txt -r requirements_test.txt
    - name: Register problem matchers
      run: |
        echo "::add-matcher::.github/workflows/matchers/ci-custom.json"

    - name: Lint
      run: python lint.py
    - name: html-strict
      run: make html-strict
